
version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=wine_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234  
    ports:
      - "5433:5432"
  app:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: wine-backend-app
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true