# Generated by Django 3.0.7 on 2021-09-28 21:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appellation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('proportion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be between 0 and 1'), django.core.validators.MaxValueValidator(limit_value=1, message='Should be between 0 and 1')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cellar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cellar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BottleCollection',
            fields=[
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rosé', 'Rose'), ('Effervescent Rosé', 'Rose Effervescent'), ('Amber', 'Amber'), ('Effervescent', 'Effervescent'), ('White Medium-Dry', 'White Medium Dry'), ('White Dry', 'White Dry'), ('Mutated Wine', 'Mutated Wine'), ('Green', 'Green')], default='Red', max_length=64)),
                ('bottle_size', models.CharField(max_length=255, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('ranking', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('soil', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('garde', models.CharField(max_length=255, null=True)),
                ('apogee', models.CharField(max_length=255, null=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('viticulture', models.CharField(choices=[('Not specified', 'Not Specified'), ('Natural', 'Natural'), ('Organic', 'Bio'), ('Organic and natural', 'Bio Nature'), ('Biodynamic', 'Biodynamism'), ('Biodynamic and natural', 'Biodynamism Natural'), ('Sustainable', 'Sustainable'), ('Conventional', 'Conventional'), ('Ecological', 'Ecological'), ('Triple A', 'Triple A'), ('Triple A and biodynamic', 'Triple A Biodynamic'), ('Triple A and organic', 'Triple A Bio')], default='Not specified', max_length=64, null=True)),
                ('alcool', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')])),
                ('vintage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')])),
                ('appellation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='business.Appellation')),
                ('grape', models.ManyToManyField(related_name='bottles', to='business.Cepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('bottle_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='business.BottleCollection')),
                ('cellar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='business.Cellar')),
            ],
            options={
                'unique_together': {('cellar', 'bottle_collection')},
            },
        ),
    ]
