# Generated by Django 3.1.5 on 2021-01-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bottle",
            name="cellar",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bottles",
                to="business.cellar",
            ),
        ),
    ]
