# Generated by Django 3.1.5 on 2021-01-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_bottle_cellar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cepage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
