# Generated by Django 3.0.7 on 2021-10-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_bottlecollection_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grape',
            old_name='proportion',
            new_name='percentage',
        ),
    ]
