# Generated by Django 3.1.5 on 2021-01-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20210105_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='cellar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='business.cellar'),
        ),
    ]
