# Generated by Django 3.1.5 on 2021-01-16 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_bottle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='degre_alcool',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')]),
        ),
        migrations.AddField(
            model_name='bottle',
            name='viticulture',
            field=models.CharField(choices=[('Not specified', 'Not Specified'), ('Natural', 'Natural'), ('Organic', 'Bio'), ('Organic and natural', 'Bio Nature'), ('Biodynamic', 'Biodynamism'), ('Biodynamic and natural', 'Biodynamism Natural'), ('Sustainable', 'Sustainable'), ('Conventional', 'Conventional'), ('Ecological', 'Ecological'), ('Triple A', 'Triple A'), ('Triple A and biodynamic', 'Triple A Biodynamic'), ('Triple A and organic', 'Triple A Bio')], default='Not specified', max_length=64),
        ),
        migrations.AddField(
            model_name='cepage',
            name='proportion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be between 0 and 1'), django.core.validators.MaxValueValidator(limit_value=1, message='Should be between 0 and 1')]),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rosé', 'Rose'), ('Effervescent Rosé', 'Rose Effervescent'), ('Amber', 'Amber'), ('Effervescent', 'Effervescent'), ('White Medium-Dry', 'White Medium Dry'), ('White Dry', 'White Dry'), ('Mutated Wine', 'Mutated Wine'), ('Green', 'Green')], default='Red', max_length=64),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')]),
        ),
    ]
