# Generated by Django 3.0.7 on 2021-02-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0008_auto_20210116_1414"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bottle",
            name="viticulture",
        ),
    ]
