# Generated by Django 3.0.7 on 2021-02-05 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_remove_bottle_viticulture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appelation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appelation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appelation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cellar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cellar',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cellar',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cepage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cepage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cepage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bottle',
            name='apogee',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='millesime',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')]),
        ),
        migrations.AddField(
            model_name='bottle',
            name='viticulture',
            field=models.CharField(choices=[('Not specified', 'Not Specified'), ('Natural', 'Natural'), ('Organic', 'Bio'), ('Organic and natural', 'Bio Nature'), ('Biodynamic', 'Biodynamism'), ('Biodynamic and natural', 'Biodynamism Natural'), ('Sustainable', 'Sustainable'), ('Conventional', 'Conventional'), ('Ecological', 'Ecological'), ('Triple A', 'Triple A'), ('Triple A and biodynamic', 'Triple A Biodynamic'), ('Triple A and organic', 'Triple A Bio')], default='Not specified', max_length=64),
        ),
    ]
