# Generated by Django 3.0.7 on 2021-02-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20210205_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='viticulture',
            field=models.CharField(choices=[('Not specified', 'Not Specified'), ('Natural', 'Natural'), ('Organic', 'Bio'), ('Organic and natural', 'Bio Nature'), ('Biodynamic', 'Biodynamism'), ('Biodynamic and natural', 'Biodynamism Natural'), ('Sustainable', 'Sustainable'), ('Conventional', 'Conventional'), ('Ecological', 'Ecological'), ('Triple A', 'Triple A'), ('Triple A and biodynamic', 'Triple A Biodynamic'), ('Triple A and organic', 'Triple A Bio')], default='Not specified', max_length=64, null=True),
        ),
    ]
