# Generated by Django 3.0.7 on 2021-02-20 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_cellar_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle',
            name='apogee',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='appelation',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='cepage',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='color',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='degre_alcool',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='millesime',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='viticulture',
        ),
        migrations.RemoveField(
            model_name='bottle',
            name='website',
        ),
        migrations.AddField(
            model_name='bottle',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BottleCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rosé', 'Rose'), ('Effervescent Rosé', 'Rose Effervescent'), ('Amber', 'Amber'), ('Effervescent', 'Effervescent'), ('White Medium-Dry', 'White Medium Dry'), ('White Dry', 'White Dry'), ('Mutated Wine', 'Mutated Wine'), ('Green', 'Green')], default='Red', max_length=64)),
                ('apogee', models.CharField(max_length=255, null=True, unique=True)),
                ('website', models.CharField(max_length=255, null=True)),
                ('viticulture', models.CharField(choices=[('Not specified', 'Not Specified'), ('Natural', 'Natural'), ('Organic', 'Bio'), ('Organic and natural', 'Bio Nature'), ('Biodynamic', 'Biodynamism'), ('Biodynamic and natural', 'Biodynamism Natural'), ('Sustainable', 'Sustainable'), ('Conventional', 'Conventional'), ('Ecological', 'Ecological'), ('Triple A', 'Triple A'), ('Triple A and biodynamic', 'Triple A Biodynamic'), ('Triple A and organic', 'Triple A Bio')], default='Not specified', max_length=64, null=True)),
                ('degre_alcool', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')])),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')])),
                ('millesime', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Should be greater than 0')])),
                ('appelation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='business.Appelation')),
                ('cepage', models.ManyToManyField(related_name='bottles', to='business.Cepage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bottle',
            name='bottle_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottle_collection', to='business.BottleCollection'),
        ),
    ]
