# Generated by Django 3.0.7 on 2021-02-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_auto_20210220_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='bottle_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='business.BottleCollection'),
        ),
    ]
