# Generated by Django 3.0.7 on 2021-02-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_auto_20210221_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bottle',
            unique_together={('cellar', 'bottle_collection')},
        ),
    ]
