# Generated by Django 3.0.7 on 2021-09-27 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_auto_20210227_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottlecollection',
            old_name='degre_alcool',
            new_name='alcool',
        ),
        migrations.RenameField(
            model_name='bottlecollection',
            old_name='cepage',
            new_name='grape',
        ),
        migrations.RenameField(
            model_name='bottlecollection',
            old_name='millesime',
            new_name='vintage',
        ),
        migrations.RemoveField(
            model_name='bottlecollection',
            name='appelation',
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='appellation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottles', to='business.Appelation'),
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='bottle_size',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='garde',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='ranking',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='soil',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bottlecollection',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bottlecollection',
            name='apogee',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bottlecollection',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
