# Generated by Django 3.0.7 on 2021-02-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('white', 'White'), ('dark', 'Dark'), ('auto', 'Auto')], default='white', max_length=64),
        ),
    ]
